import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

// const satoshi = localFont({
//   src: [
//     {
//       path: "./fonts/Satoshi-Regular.woff",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./fonts/Satoshi-Medium.woff",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "./fonts/Satoshi-Bold.woff",
//       weight: "700",
//       style: "normal",
//     },
//   ],
// });

export const metadata: Metadata = {
  title: "Next Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} bg-[#fafafa]`}>{children}</body>
    </html>
  );
}
